
/*

prisma/schema.prisma のスキーマ変更時

npx prisma db push

*/

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const dbConfig = {
  host: process.env.NS_MARIADB_HOSTNAME || 'localhost',
  port: process.env.NS_MARIADB_PORT || 3306,
  user: process.env.NS_MARIADB_USER, // ※ユーザー名も変数化推奨
  password: process.env.NS_MARIADB_PASSWORD,
  database: process.env.NS_MARIADB_DATABASE,
};

// 接続先URLが必要な場合はここで組み立てる
const databaseUrl = `mysql://${dbConfig.user}:${dbConfig.password}@${dbConfig.host}:${dbConfig.port}/${dbConfig.database}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
